# Site settings
description: A blog about TangGuowei
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tangguowei.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Tom
user_description: A Developer From CHN 
user_title: A Developer
email: tanggw@gmail.com
twitter_username: tomgwtang
github_username:  TangGuowei
gplus_username: Guowei Tang
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
